import type { SignedBrief } from "@altai/contracts";
import { money, pct, shorten, mdCell, mdText } from "./util";

/** A human-readable, provenance-stamped brief. Reads like an analyst note and carries
 * the cryptographic attestation in its footer. All entity-controlled strings are
 * escaped (no raw HTML, no table/`code` breakouts) — defense in depth on top of the
 * membrane, which already scrubbed the underlying signal. */
export function briefToMarkdown(brief: SignedBrief): string {
  const { signal } = brief;
  const code = (s: string) => `\`${s.replace(/`/g, "")}\``; // safe inline code (no backtick breakout)
  const title = `${mdText(signal.entity)}${signal.ticker ? ` (${mdCell(signal.ticker)})` : ""}`;
  const L: string[] = [];

  L.push(`# Altai Intelligence Brief`);
  L.push("");
  L.push(`**${title}** — ${code(signal.event_type)}`);
  L.push("");
  L.push(`> ${mdText(signal.summary)}`);
  L.push("");

  L.push(`| Field | Value |`);
  L.push(`|---|---|`);
  L.push(`| Confidence (${signal.confidence_method}) | **${pct(signal.confidence)}** |`);
  L.push(`| Observed | ${signal.observed_at} |`);
  if (signal.disclosed_at) L.push(`| Publicly disclosed | ${signal.disclosed_at} |`);
  if (signal.lead_time_days != null) L.push(`| Lead time | **${signal.lead_time_days} days before the market** |`);
  L.push(`| Independent sources | ${signal.sources.length} |`);
  L.push("");

  if (signal.alpha) {
    const a = signal.alpha;
    L.push(`## Alpha — ${mdText(a.strategy)}`);
    L.push("");
    L.push(`| Entry | Exit | Return | Max drawdown |`);
    L.push(`|---|---|---|---|`);
    L.push(`| ${mdCell(a.entry_date)} @ ${money(a.entry_price)} | ${mdCell(a.exit_date)} @ ${money(a.exit_price)} | ${a.return_pct != null ? `**${a.return_pct}%**` : "—"} | ${a.max_drawdown_pct != null ? `${a.max_drawdown_pct}%` : "—"} |`);
    if (a.note) {
      L.push("");
      L.push(`_${mdText(a.note)}_`);
    }
    L.push("");
  }

  L.push(`## Corroborating sources`);
  L.push("");
  L.push(`| Source | Type | Reliability | Observed | URL |`);
  L.push(`|---|---|---|---|---|`);
  for (const s of signal.sources) {
    L.push(`| ${mdCell(s.name)} | ${code(s.type)} | ${s.reliability.toFixed(2)} | ${mdCell(s.observed_at)} | ${mdCell(s.url ?? "—")} |`);
  }
  L.push("");

  L.push(`## Provenance & attestation`);
  L.push("");
  L.push(`- **Signature:** Ed25519 — \`${shorten(brief.signature)}\``);
  L.push(`- **Audit root (Merkle):** \`${shorten(brief.audit_root)}\``);
  L.push(`- **Public key:** \`${shorten(brief.public_key.replace(/\s+/g, " "))}\``);
  L.push(`- Tamper-evident: altering any audit entry breaks the recomputed Merkle root while the signature stays valid.`);
  L.push("");
  L.push(`_Generated by **Altai** — the sovereign external-action layer for air-gapped enterprise AI agents._`);
  L.push("");

  return L.join("\n");
}
