import type { SignedBrief } from "@altai/contracts";
import { money, pct, shorten } from "./util";

/** A human-readable, provenance-stamped brief. Reads like an analyst note and carries
 * the cryptographic attestation in its footer. */
export function briefToMarkdown(brief: SignedBrief): string {
  const { signal } = brief;
  const title = `${signal.entity}${signal.ticker ? ` (${signal.ticker})` : ""}`;
  const L: string[] = [];

  L.push(`# Altai Intelligence Brief`);
  L.push("");
  L.push(`**${title}** — \`${signal.event_type}\``);
  L.push("");
  L.push(`> ${signal.summary}`);
  L.push("");

  L.push(`| Field | Value |`);
  L.push(`|---|---|`);
  L.push(`| Confidence (${signal.confidence_method}) | **${pct(signal.confidence)}** |`);
  L.push(`| Observed | ${signal.observed_at} |`);
  if (signal.disclosed_at) L.push(`| Publicly disclosed | ${signal.disclosed_at} |`);
  if (signal.lead_time_days != null) L.push(`| Lead time | **${signal.lead_time_days} days before the market** |`);
  L.push(`| Independent sources | ${signal.sources.length} |`);
  L.push("");

  if (signal.alpha) {
    const a = signal.alpha;
    L.push(`## Alpha — ${a.strategy}`);
    L.push("");
    L.push(`| Entry | Exit | Return | Max drawdown |`);
    L.push(`|---|---|---|---|`);
    L.push(`| ${a.entry_date} @ ${money(a.entry_price)} | ${a.exit_date} @ ${money(a.exit_price)} | ${a.return_pct != null ? `**${a.return_pct}%**` : "—"} | ${a.max_drawdown_pct != null ? `${a.max_drawdown_pct}%` : "—"} |`);
    if (a.note) {
      L.push("");
      L.push(`_${a.note}_`);
    }
    L.push("");
  }

  L.push(`## Corroborating sources`);
  L.push("");
  L.push(`| Source | Type | Reliability | Observed | URL |`);
  L.push(`|---|---|---|---|---|`);
  for (const s of signal.sources) {
    L.push(`| ${s.name} | \`${s.type}\` | ${s.reliability.toFixed(2)} | ${s.observed_at} | ${s.url ?? "—"} |`);
  }
  L.push("");

  L.push(`## Provenance & attestation`);
  L.push("");
  L.push(`- **Signature:** Ed25519 — \`${shorten(brief.signature)}\``);
  L.push(`- **Audit root (Merkle):** \`${shorten(brief.audit_root)}\``);
  L.push(`- **Public key:** \`${shorten(brief.public_key.replace(/\s+/g, " "))}\``);
  L.push(`- Tamper-evident: altering any audit entry breaks the recomputed Merkle root while the signature stays valid.`);
  L.push("");
  L.push(`_Generated by **Altai** — the sovereign external-action layer for air-gapped enterprise AI agents._`);
  L.push("");

  return L.join("\n");
}
